#!/usr/bin/env python3
"""Build metric JSON for the final four-bar Figure 8.

The script is self-contained for the AE hardware package:

The script reads simulator per-problem CSVs, weak BBeam1 token logs, and
per-problem energy CSVs. It only writes metric summaries; the final plot is
generated by ``figure8/plot_figure8.py``.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import statistics
from pathlib import Path
from typing import Any, Dict, Iterable, List


SCRIPT_DIR = Path(__file__).resolve().parent
AE_ROOT = SCRIPT_DIR.parent
DEFAULT_TOKEN_ROOT = AE_ROOT / "inputs" / "token_logs"
DEFAULT_SIM_OUTPUT_DIR = AE_ROOT / "outputs" / "simulator_latency"
DEFAULT_ENERGY_DIR = AE_ROOT / "outputs" / "energy"
DEFAULT_OUTPUT_DIR = AE_ROOT / "outputs" / "figure8"

DATASETS = ["math500", "gsm8k", "gaokao2023en", "olympiadbench"]
DATASET_LABELS = {
    "math500": "Math500",
    "gsm8k": "GSM8K",
    "gaokao2023en": "Gaokao23",
    "olympiadbench": "Olympiad",
    "average": "Avg",
}
CONFIGS = {
    "Config1": {
        "title": "Config1: 0.5B draft - 7B PRM - 7B Target",
        "token_dir": "weak_config1",
        "sim_prefix": "config1",
        "energy_dir": "config1",
    },
    "Config2": {
        "title": "Config2: 0.5B draft - 7B PRM - 1.5B Target",
        "token_dir": "weak_config2",
        "sim_prefix": "config2",
        "energy_dir": "config2",
    },
}
METHODS = ["weak_baseline", "strong_baseline", "ours"]
METHOD_LABELS = {
    "weak_baseline": "Weak baseline",
    "strong_baseline": "Strong baseline",
    "ours": "Ours",
}
SIM_COLUMNS = {
    "weak_baseline": "weak",
    "strong_baseline": "strong",
    "ours": "our",
}
ENERGY_COLUMNS = {
    "weak_baseline": "weak_power",
    "strong_baseline": "strong_power",
    "ours": "our_power",
}
COLORS = {
    "weak_baseline": "#d3d3d3",
    "strong_baseline": "#9ecae1",
    "ours": "#5b9bd5",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--token-root", type=Path, default=DEFAULT_TOKEN_ROOT)
    parser.add_argument("--sim-output-dir", type=Path, default=DEFAULT_SIM_OUTPUT_DIR)
    parser.add_argument("--energy-dir", type=Path, default=DEFAULT_ENERGY_DIR)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--normalized",
        action="store_true",
        help="Plot each metric relative to the weak baseline for the same config/dataset.",
    )
    parser.add_argument("--no-plot", action="store_true")
    return parser.parse_args()


def normalize_id(value: Any) -> str:
    if value is None:
        return ""
    text = str(value).strip()
    if text == "":
        return ""
    try:
        numeric = float(text)
    except ValueError:
        return text
    return str(int(numeric)) if numeric.is_integer() else text


def sort_ids(ids: Iterable[str]) -> List[str]:
    return sorted(ids, key=lambda item: int(item) if item.isdigit() else item)


def mean(values: Iterable[float]) -> float:
    values = list(values)
    return statistics.fmean(values) if values else math.nan


def load_goodput_by_id(path: Path) -> Dict[str, int]:
    if not path.exists():
        raise FileNotFoundError(path)
    records: Dict[str, int] = {}
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            sample = json.loads(line)
            token_counts = sample.get("token_counts")
            if not isinstance(token_counts, list) or len(token_counts) < 2:
                raise ValueError(f"Missing token_counts[0:2] in {path}:{line_number}")
            sample_id = normalize_id(sample.get("idx")) or str(len(records))
            if sample_id in records:
                raise ValueError(f"Duplicate sample id {sample_id} in {path}")
            records[sample_id] = int(token_counts[0]) + int(token_counts[1])
    if not records:
        raise ValueError(f"No valid samples in {path}")
    return records


def load_simulator_by_id(path: Path) -> Dict[str, Dict[str, float]]:
    if not path.exists():
        raise FileNotFoundError(path)
    records: Dict[str, Dict[str, float]] = {}
    with path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            pid = row.get("problem_ordinal", "")
            if pid in {"TOTAL", "MEAN_OF_PROBLEMS"}:
                continue
            sample_id = normalize_id(row.get("example_idx")) or normalize_id(pid)
            if sample_id == "":
                raise ValueError(f"Missing problem id in {path}")
            if sample_id in records:
                raise ValueError(f"Duplicate simulator sample id {sample_id} in {path}")
            records[sample_id] = {
                method: float(row[column]) / 1000.0
                for method, column in SIM_COLUMNS.items()
            }
    if not records:
        raise ValueError(f"No simulator rows in {path}")
    return records


def find_energy_file(energy_dir: Path, config: str, dataset: str) -> Path:
    config_dir = energy_dir / CONFIGS[config]["energy_dir"]
    candidates = sorted(config_dir.glob(f"*_{dataset}_step_profile*_per_problem.csv"))
    candidates = [path for path in candidates if "bbeam1" in path.name]
    if not candidates:
        raise FileNotFoundError(
            f"No energy per-problem CSV for {config}/{dataset} under {config_dir}"
        )
    if len(candidates) == 1:
        return candidates[0]
    return max(candidates, key=lambda path: path.stat().st_mtime)


def load_energy_by_method(path: Path) -> Dict[str, Dict[str, Any]]:
    totals = {method: 0.0 for method in METHODS}
    n_problems = 0
    with path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            if row.get("problem_ordinal") in {"TOTAL", "MEAN_OF_PROBLEMS"}:
                continue
            if not row.get("problem_ordinal"):
                continue
            n_problems += 1
            for method, column in ENERGY_COLUMNS.items():
                totals[method] += float(row[column])
    if n_problems <= 0:
        raise ValueError(f"No per-problem energy rows in {path}")
    return {
        method: {
            "n_energy_problems": n_problems,
            "total_energy_j": totals[method],
            "avg_energy_j_per_problem": totals[method] / n_problems,
            "avg_energy_kj_per_problem": totals[method] / n_problems / 1000.0,
            "energy_source": str(path),
        }
        for method in METHODS
    }


def aggregate_method(
    sim_records: Dict[str, Dict[str, float]],
    goodput_by_id: Dict[str, int],
    selected_ids: set[str],
    method: str,
    latency_source: Path,
    token_source: Path,
) -> Dict[str, Any]:
    ids = sort_ids(selected_ids)
    total_latency_s = sum(sim_records[sample_id][method] for sample_id in ids)
    goodput_tokens = sum(goodput_by_id[sample_id] for sample_id in ids)
    n_problems = len(ids)
    if n_problems == 0 or total_latency_s <= 0.0:
        raise ValueError(f"No selected samples for {latency_source} / {method}")
    return {
        "n_problems": n_problems,
        "total_latency_s": total_latency_s,
        "avg_latency_s": total_latency_s / n_problems,
        "goodput_tokens": goodput_tokens,
        "throughput_tokens_s": goodput_tokens / total_latency_s,
        "latency_source": str(latency_source),
        "token_source": str(token_source),
    }


def build_metrics(
    token_root: Path,
    sim_output_dir: Path,
    energy_dir: Path,
    normalized: bool,
) -> Dict[str, Any]:
    metrics: Dict[str, Any] = {
        "schema_version": 1,
        "description": (
            "AE hardware Figure 8 metrics. Latency is read from simulator "
            "per-problem CSVs, goodput uses token_counts[0]+token_counts[1] "
            "from weak BBeam1 logs, and energy uses per-problem CSVs."
        ),
        "plot_normalized_to_weak": normalized,
        "dataset_order": DATASETS,
        "dataset_labels": DATASET_LABELS,
        "configs": {},
    }

    for config, info in CONFIGS.items():
        config_metrics: Dict[str, Any] = {
            "title": info["title"],
            "datasets": {},
            "mean_of_datasets": {},
            "pooled_total": {},
            "warnings": [],
        }
        method_records: Dict[str, List[Dict[str, Any]]] = {method: [] for method in METHODS}

        for dataset in DATASETS:
            token_source = token_root / info["token_dir"] / f"{dataset}.jsonl"
            sim_source = sim_output_dir / f"{info['sim_prefix']}_{dataset}_target_overlap_per_problem.csv"
            goodput_by_id = load_goodput_by_id(token_source)
            sim_records = load_simulator_by_id(sim_source)
            selected_ids = set(goodput_by_id) & set(sim_records)
            if len(selected_ids) != len(goodput_by_id):
                config_metrics["warnings"].append(
                    f"{config}/{dataset}: using {len(selected_ids)} simulator-aligned "
                    f"problems; token log has {len(goodput_by_id)}"
                )
            if len(selected_ids) != len(sim_records):
                config_metrics["warnings"].append(
                    f"{config}/{dataset}: using {len(selected_ids)} simulator-aligned "
                    f"problems; simulator output has {len(sim_records)}"
                )

            records = {
                method: aggregate_method(
                    sim_records,
                    goodput_by_id,
                    selected_ids,
                    method,
                    sim_source,
                    token_source,
                )
                for method in METHODS
            }

            energy_file = find_energy_file(energy_dir, config, dataset)
            energy_by_method = load_energy_by_method(energy_file)
            for method in METHODS:
                records[method].update(energy_by_method[method])
                if int(records[method]["n_problems"]) != int(records[method]["n_energy_problems"]):
                    config_metrics["warnings"].append(
                        f"{config}/{dataset}/{method}: latency/goodput uses "
                        f"{records[method]['n_problems']} problems but energy uses "
                        f"{records[method]['n_energy_problems']} problems"
                    )

            config_metrics["datasets"][dataset] = records
            for method, record in records.items():
                method_records[method].append(record)

        for method, records in method_records.items():
            total_latency_s = sum(float(r["total_latency_s"]) for r in records)
            goodput_tokens = sum(int(r["goodput_tokens"]) for r in records)
            n_problems = sum(int(r["n_problems"]) for r in records)
            total_energy_j = sum(float(r["total_energy_j"]) for r in records)
            n_energy_problems = sum(int(r["n_energy_problems"]) for r in records)
            config_metrics["mean_of_datasets"][method] = {
                "avg_latency_s": mean(float(r["avg_latency_s"]) for r in records),
                "throughput_tokens_s": mean(float(r["throughput_tokens_s"]) for r in records),
                "avg_energy_j_per_problem": mean(float(r["avg_energy_j_per_problem"]) for r in records),
                "avg_energy_kj_per_problem": mean(
                    float(r["avg_energy_kj_per_problem"]) for r in records
                ),
            }
            config_metrics["pooled_total"][method] = {
                "n_problems": n_problems,
                "total_latency_s": total_latency_s,
                "avg_latency_s": total_latency_s / n_problems,
                "goodput_tokens": goodput_tokens,
                "throughput_tokens_s": goodput_tokens / total_latency_s,
                "n_energy_problems": n_energy_problems,
                "total_energy_j": total_energy_j,
                "avg_energy_j_per_problem": total_energy_j / n_energy_problems,
                "avg_energy_kj_per_problem": total_energy_j / n_energy_problems / 1000.0,
            }

        metrics["configs"][config] = config_metrics

    return metrics


def values_for_plot(metrics: Dict[str, Any], config: str, method: str, metric: str) -> List[float]:
    values = [
        float(metrics["configs"][config]["datasets"][dataset][method][metric])
        for dataset in DATASETS
    ]
    values.append(float(metrics["configs"][config]["mean_of_datasets"][method][metric]))
    return values


def normalize_to_weak(method_values: Dict[str, List[float]]) -> Dict[str, List[float]]:
    weak_values = method_values["weak_baseline"]
    return {
        method: [
            value / weak if weak > 0.0 else math.nan
            for value, weak in zip(values, weak_values)
        ]
        for method, values in method_values.items()
    }


def add_ratio_arrows(
    ax: Any,
    x_positions: List[int],
    weak_values: List[float],
    strong_values: List[float],
    ours_values: List[float],
    bar_width: float,
    higher_better: bool,
) -> None:
    y_min, y_max = ax.get_ylim()
    y_span = y_max - y_min
    text_shift = y_span * 0.012
    for i, xpos in enumerate(x_positions):
        ours = ours_values[i]
        ax.hlines(
            ours,
            xpos - bar_width * 1.25,
            xpos + bar_width * 1.25,
            colors="red",
            linestyles="--",
            linewidth=0.9,
            alpha=0.8,
        )
        for baseline, arrow_x in [
            (weak_values[i], xpos - bar_width * 1.15),
            (strong_values[i], xpos + bar_width * 0.10),
        ]:
            if baseline <= 0 or ours <= 0:
                continue
            ratio = (ours / baseline) if higher_better else (baseline / ours)
            ax.annotate(
                "",
                xy=(arrow_x, ours),
                xytext=(arrow_x, baseline),
                arrowprops=dict(arrowstyle="->", color="red", lw=1.0),
            )
            mid_y = (baseline + ours) / 2.0
            if abs(baseline - ours) < y_span * 0.035:
                mid_y = max(baseline, ours) + text_shift
            mid_y = min(max(mid_y, y_min + text_shift), y_max - text_shift)
            ax.text(
                arrow_x + 0.025,
                mid_y,
                f"{ratio:.2f}x",
                color="red",
                ha="left",
                va="center",
                fontsize=7,
                clip_on=True,
            )


def plot(metrics: Dict[str, Any], output_dir: Path, normalized: bool) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    labels = [DATASET_LABELS[d] for d in DATASETS] + [DATASET_LABELS["average"]]
    x_positions = list(range(len(labels)))
    bar_width = 0.24
    metric_specs = [
        ("avg_latency_s", "Latency (s)", "Normalized Latency (Weak=1)", False),
        ("throughput_tokens_s", "Goodput Throughput (token/s)", "Normalized Goodput (Weak=1)", True),
        ("avg_energy_kj_per_problem", "Energy (kJ/problem)", "Normalized Energy (Weak=1)", False),
    ]
    fig, axes = plt.subplots(3, 2, figsize=(12, 10.0))
    for row_idx, (metric, ylabel, normalized_ylabel, higher_better) in enumerate(metric_specs):
        for col_idx, config in enumerate(["Config1", "Config2"]):
            ax = axes[row_idx][col_idx]
            method_values = {
                method: values_for_plot(metrics, config, method, metric)
                for method in METHODS
            }
            if normalized:
                method_values = normalize_to_weak(method_values)
            for offset, method in zip((-bar_width, 0.0, bar_width), METHODS):
                ax.bar(
                    [x + offset for x in x_positions],
                    method_values[method],
                    bar_width,
                    label=METHOD_LABELS[method],
                    color=COLORS[method],
                    edgecolor="black",
                    linewidth=0.6,
                )
            ax.set_xticks(x_positions)
            ax.set_xticklabels(labels, fontsize=9)
            ax.set_ylabel(normalized_ylabel if normalized else ylabel, fontsize=11)
            ax.grid(axis="y", linestyle="--", alpha=0.35)
            ax.set_axisbelow(True)
            if row_idx == 0:
                ax.set_title(metrics["configs"][config]["title"], fontsize=12, fontweight="bold")
            all_values = [value for values in method_values.values() for value in values]
            y_top = max(all_values) * (1.20 if higher_better else 1.15)
            if normalized:
                y_top = max(y_top, 1.18)
            ax.set_ylim(0, y_top)
            add_ratio_arrows(
                ax,
                x_positions,
                method_values["weak_baseline"],
                method_values["strong_baseline"],
                method_values["ours"],
                bar_width,
                higher_better,
            )

    handles, legend_labels = axes[0][0].get_legend_handles_labels()
    fig.legend(
        handles,
        legend_labels,
        loc="upper center",
        bbox_to_anchor=(0.5, 1.0),
        ncol=3,
        frameon=True,
        edgecolor="black",
        fontsize=11,
    )
    fig.tight_layout(rect=[0, 0, 1, 0.94])
    output_dir.mkdir(parents=True, exist_ok=True)
    output_stem = (
        "figure8_simulator_goodput_energy_normalized"
        if normalized
        else "figure8_simulator_goodput_energy"
    )
    fig.savefig(output_dir / f"{output_stem}.png", dpi=300)
    fig.savefig(output_dir / f"{output_stem}.pdf")
    plt.close(fig)


def metric_rows(metrics: Dict[str, Any]) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for config, config_metrics in metrics["configs"].items():
        for dataset in DATASETS:
            for method in METHODS:
                record = config_metrics["datasets"][dataset][method]
                rows.append(
                    {
                        "row_type": "dataset",
                        "config": config,
                        "dataset": dataset,
                        "method": method,
                        "n_problems": record["n_problems"],
                        "total_latency_s": f"{record['total_latency_s']:.6f}",
                        "avg_latency_s": f"{record['avg_latency_s']:.6f}",
                        "goodput_tokens": record["goodput_tokens"],
                        "throughput_tokens_s": f"{record['throughput_tokens_s']:.6f}",
                        "n_energy_problems": record["n_energy_problems"],
                        "total_energy_j": f"{record['total_energy_j']:.6f}",
                        "avg_energy_j_per_problem": f"{record['avg_energy_j_per_problem']:.6f}",
                        "avg_energy_kj_per_problem": f"{record['avg_energy_kj_per_problem']:.6f}",
                    }
                )
        for method in METHODS:
            record = config_metrics["pooled_total"][method]
            rows.append(
                {
                    "row_type": "pooled_total",
                    "config": config,
                    "dataset": "all",
                    "method": method,
                    "n_problems": record["n_problems"],
                    "total_latency_s": f"{record['total_latency_s']:.6f}",
                    "avg_latency_s": f"{record['avg_latency_s']:.6f}",
                    "goodput_tokens": record["goodput_tokens"],
                    "throughput_tokens_s": f"{record['throughput_tokens_s']:.6f}",
                    "n_energy_problems": record["n_energy_problems"],
                    "total_energy_j": f"{record['total_energy_j']:.6f}",
                    "avg_energy_j_per_problem": f"{record['avg_energy_j_per_problem']:.6f}",
                    "avg_energy_kj_per_problem": f"{record['avg_energy_kj_per_problem']:.6f}",
                }
            )
    return rows


def write_csv_rows(path: Path, rows: List[Dict[str, Any]]) -> None:
    fieldnames = [
        "row_type",
        "config",
        "dataset",
        "method",
        "n_problems",
        "total_latency_s",
        "avg_latency_s",
        "goodput_tokens",
        "throughput_tokens_s",
        "n_energy_problems",
        "total_energy_j",
        "avg_energy_j_per_problem",
        "avg_energy_kj_per_problem",
    ]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def print_summary(metrics: Dict[str, Any]) -> None:
    for config in ["Config1", "Config2"]:
        print(f"\n{config}")
        print(
            "%-16s %9s %12s %12s %12s %14s"
            % ("method", "problems", "total_s", "avg_lat_s", "goodput_t/s", "kJ/problem")
        )
        print("-" * 88)
        for method in METHODS:
            record = metrics["configs"][config]["pooled_total"][method]
            print(
                "%-16s %9d %12.2f %12.4f %12.2f %14.2f"
                % (
                    method,
                    record["n_problems"],
                    record["total_latency_s"],
                    record["avg_latency_s"],
                    record["throughput_tokens_s"],
                    record["avg_energy_kj_per_problem"],
                )
            )
        pooled = metrics["configs"][config]["pooled_total"]
        print(
            "Energy ratio (pooled): weak/ours=%.4fx, strong/ours=%.4fx"
            % (
                pooled["weak_baseline"]["total_energy_j"] / pooled["ours"]["total_energy_j"],
                pooled["strong_baseline"]["total_energy_j"] / pooled["ours"]["total_energy_j"],
            )
        )
        for warning in metrics["configs"][config]["warnings"]:
            print(f"WARNING: {warning}")


def main() -> None:
    args = parse_args()
    if not args.no_plot:
        raise SystemExit("Use --no-plot: this helper only builds metric JSON files.")
    args.output_dir.mkdir(parents=True, exist_ok=True)
    metrics = build_metrics(
        args.token_root,
        args.sim_output_dir,
        args.energy_dir,
        args.normalized,
    )
    rows = metric_rows(metrics)
    output_stem = (
        "figure8_simulator_goodput_energy_normalized"
        if args.normalized
        else "figure8_simulator_goodput_energy"
    )
    json_path = args.output_dir / f"{output_stem}_metrics.json"
    csv_path = args.output_dir / f"{output_stem}_metrics.csv"
    json_path.write_text(json.dumps(metrics, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_csv_rows(csv_path, rows)
    print_summary(metrics)
    print(f"\nWrote {json_path}")
    print(f"Wrote {csv_path}")


if __name__ == "__main__":
    main()
